name: Continuous Integration

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            flagCompiler: -G"Visual Studio 17 2022"
            name: Windows VS2022
          - os: windows-latest
            flagCompiler: -G"MinGW Makefiles"
            name: Windows MinGW
          - os: ubuntu-latest
            name: Linux

    steps:
      - name: Install Linux Dependencies
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: |
          sudo apt-get update
          sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev

      - name: Install CMake 4.2.1
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.2.1
      
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure
        run: cmake -B build ${{matrix.flagCompiler}}

      - name: Build
        run: cmake --build build --config Release